# Identifying special matrices
## Instructions
В этом задании вы напишите функцию, которая будет проверять перед вычислением матрицы  4×4, не будет ли она сингулярной, то есть, существует ли к ней инверсия.

Используйте метод преобразования матрицы к эшелонированной по строкам форме и проверки, если это не удастся, оставив нули, которые нельзя удалить на главной диагонали.
Не беспокойтесь, если вы раньше не программировали, фреймворк для функции уже написан.
В коде отмечены места, где надо внести изменения.
Первые две строки уже написаны, можно использовать их как подсказку, чтобы сделать последние две.

### Матрицы в Python
В пакете *numpy* в Python индексация матриц начинается с нуля для самого верхнего столбца и самой левой строки.
Т.е. матричная структура выглядит так:

```python
A[0, 0]  A[0, 1]  A[0, 2]  A[0, 3]
A[1, 0]  A[1, 1]  A[1, 2]  A[1, 3]
A[2, 0]  A[2, 1]  A[2, 2]  A[2, 3]
A[3, 0]  A[3, 1]  A[3, 2]  A[3, 3]
```
Вы можете получить доступ к значению каждого элемента в отдельности, используя
```python
A[n, m]
```
который даст n-ую строку и m-й столбец (начиная с нуля).

Вы также можете получить доступ ко всей строке одновременно, используя
```python
A[n]
```
как вы увидите, это будет полезно при расчете линейных комбинаций строк.

Последнее примечание - Python чувствителен к отступам.
Весь код, который надо написать, должен быть на том же уровне отступа, что и комментарий с инструкциями.

Пожалуйста, не меняйте имена функций.
Удачи!

In [ ]:
# GRADED FUNCTION
import numpy as np

# Наша функция будет проходить через матрицу, изменяя каждую строку так, чтобы привести матрицу к эшелонированной форме.
# Если в какой-то момент она не сможет поставить 1 в главную диагональ,
# мы вернем значение True, в противном случае мы вернем False.
# Эту функцию изменять не надо.


def isSingular(A) :
    B =  np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_) #  Делает B как копию матрицы A, так как мы будем менять ее значения.
    try:
        fixRowZero(B)
        fixRowOne(B)
        fixRowTwo(B)
        fixRowThree(B)
    except MatrixIsSingular:
        return True
    return False

# Следующая строка определяет наш флаг ошибки, когда что-то идет не так, и это значит матрица сингулярная.
# Нет необходимости редактировать эту строку.
class MatrixIsSingular(Exception): pass
# Для Row Zero все, что нам нужно, это первый элемент, равный 1.
# Мы разделим строку на значение A [0, 0].
# Однако, если A [0, 0] равно 0, это доставит нам неприятности, поэтому сначала мы ее проверим на ноль,
# и если это так,  перед делением мы прибавим одну из нижних строк к первой.
# Будем повторять проверку для каждого ряда снизу, пока деление не станет возможным. Если так и не найдем нужную строку, значит, матрица сингулярна
# Нет необходимости редактировать эту функцию.

def fixRowZero(A) :
    if A[0,0] == 0 :
        A[0] = A[0] + A[1]
    if A[0,0] == 0 :
        A[0] = A[0] + A[2]
    if A[0,0] == 0 :
        A[0] = A[0] + A[3]
    if A[0,0] == 0 :
        raise MatrixIsSingular()
    A[0] = A[0] / A[0,0]
    return A

# Сначала мы установим элементы под главной диагональю в ноль, то есть A [1,0].
# Далее нам надо, чтобы элемент на диагонали был равен единице, и мы разделим строку на значение A [1, 1].
# Опять же, нам нужно проверить, не ноль ли это.
# Если это так, мы прибавим нижнюю строку и повторим установку поддиагональных элементов в ноль.
# Нет необходимости редактировать эту функцию.
def fixRowOne(A) :
    A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[2]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        A[1] = A[1] + A[3]
        A[1] = A[1] - A[1,0] * A[0]
    if A[1,1] == 0 :
        raise MatrixIsSingular()
    A[1] = A[1] / A[1,1]
    return A

# Это первая функция, которую вы должны выполнить.
# Следуйте инструкциям внутри функции при каждом комментарии
def fixRowTwo(A) :
    # Вставьте код ниже, чтобы установить поддиагональные элементы второй строки в ноль (их два).
      A[2]=A[2]-A[2,0]*A[0]
      A[2]=A[2]-A[2,1]*A[1]
    # Далее мы проверим, что диагональный элемент не равен нулю.
      if A[2,2] == 0 :
        # Вставьте код ниже, который добавляет нижнюю строку в строку 2.
        A[2]=A[2]+A[3]
        A[2]=A[2]-A[2,0]*A[0]
        A[2]=A[2]-A[2,1]*A[1]
        # Теперь повторите ваш код, который устанавливает поддиагональные элементы на ноль.
                
      if A[2,2] == 0 :
        raise MatrixIsSingular()
    # Наконец, установите диагональный элемент в единицу, разделив всю строку на этот элемент.
      A[2]=A[2] / A[2,2]
      return A

# Вы также должны сами выполнить эту функцию
# Следуйте инструкциям внутри функции.
def fixRowThree(A) :
    # Вставьте код ниже, чтобы установить субдиагональные элементы строки три в ноль.
    
    A[3]=A[3]-A[3,0]*A[0]
    A[3]=A[3]-A[3,1]*A[1]
    A[3]=A[3]-A[3,2]*A[2]
    
    # Завершите оператор if, чтобы проверить, равен ли диагональный элемент нулю.
    if A[3,3] == 0 :
        raise MatrixIsSingular()
    # Преобразуйте строку, чтобы установить диагональный элемент в единицу.
    A[3]=A[3]/A[3,3]
    return A

## Проверьте свой код перед отправкой
Чтобы проверить код, который вы написали выше, запустите ячейку (выберите ячейку выше, затем нажмите кнопку воспроизведения [▶ |] или нажмите Shift-Enter).
Затем вы можете использовать приведенный ниже код для проверки вашей функции.
Эта ячейка не оценивается; можете изменять и запускать ее сколько угодно.

Попробуйте свой код на сложных тестовых случаях!


In [ ]:
A = np.array([
        [2, 0, 0, 0],
        [0, 3, 0, 0],
        [0, 0, 4, 4],
        [0, 0, 5, 5]
    ], dtype=np.float_)
isSingular(A)

True

In [ ]:
A = np.array([
        [0, 7, -5, 3],
        [2, 8, 0, 4],
        [3, 12, 0, 5],
        [1, 3, 1, 3]
    ], dtype=np.float_)
fixRowZero(A)

array([[ 1. ,  7.5, -2.5,  3.5],
       [ 2. ,  8. ,  0. ,  4. ],
       [ 3. , 12. ,  0. ,  5. ],
       [ 1. ,  3. ,  1. ,  3. ]])

In [ ]:
fixRowOne(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 3.        , 12.        ,  0.        ,  5.        ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [ ]:
fixRowTwo(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 1.        ,  3.        ,  1.        ,  3.        ]])

In [ ]:
fixRowThree(A)

array([[ 1.        ,  7.5       , -2.5       ,  3.5       ],
       [-0.        ,  1.        , -0.71428571,  0.42857143],
       [ 0.        ,  0.        ,  1.        ,  1.5       ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])